# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/cryptix/wav";
    fetch = {
      type = "git";
      url = "https://github.com/cryptix/wav";
      rev = "8bdace674401f0bd3b63c65479b6a6ff1f9d5e44";
      sha256 = "18nyqv0ic35fs9fny8sj84c00vbxs8mnric6vr6yl42624fh5id6";
    };
  }
  {
    goPackagePath = "github.com/linuxdeepin/go-x11-client";
    fetch = {
      type = "git";
      url = "https://github.com/linuxdeepin/go-x11-client";
      rev = "b5b01565d224d5ccd5a4143d9099acceb23e182a";
      sha256 = "1lnffjp8bqy6f8caw6drg1js6hny5w7432riqchcrcd4q85d94rs";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "3b0461eec859c4b73bb64fdc8285971fd33e3938";
      sha256 = "0l00c8l0a8xnv6qdpwfzxxsr58jggacgzdrwiprrfx2xqm37b6d5";
    };
  }
]
